import { writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const errorsDocPath = path.join(root, 'docs', 'errors.md');

export const MEANINGS = {
  VSUP_CONFIG_INVALID: 'The configuration file is missing a required field, has an invalid value or cannot be parsed.',
  VSUP_VIBE_NOT_FOUND: 'The vibe executable was not found on PATH or at paths.vibe.',
  VSUP_VIBE_ACP_NOT_FOUND: 'The vibe-acp executable was not found on PATH or at paths.vibe_acp.',
  VSUP_VIBE_VERSION_UNSUPPORTED: 'The installed Vibe is not the pinned version.',
  VSUP_ACP_INIT_FAILED: 'The ACP connection failed before the session was ready.',
  VSUP_ACP_VERSION_UNSUPPORTED: 'Vibe ACP negotiated an unsupported ACP protocol version.',
  VSUP_ACP_PROTOCOL_ERROR: 'The ACP connection failed after the session was ready.',
  VSUP_AUTH_REQUIRED: 'Vibe reported a missing or rejected credential (401, unauthorized, missing API key).',
  VSUP_WORKSPACE_INVALID: 'The workspace or a context file does not exist or lies outside every allowed root, contains project .vibe, a symlink or non-directory .agents, a symlinked .vibeignore or glob characters in its path, or an edit run did not start at the git repository root.',
  VSUP_WORKTREE_CREATE_FAILED: 'git worktree add failed for the edit run; details.stderr_tail and details.operation say why.',
  VSUP_GIT_REQUIRED: 'The git executable is missing.',
  VSUP_PERMISSION_REQUIRED: 'A permission decision is pending; the action cannot proceed until it is answered.',
  VSUP_INPUT_REQUIRED: 'An input request is pending; the action cannot proceed until it is answered.',
  VSUP_REQUEST_EXPIRED: 'The permission or input request is no longer pending, for example after a restart.',
  VSUP_SESSION_NOT_RESUMABLE: 'The saved backend session cannot be continued or reloaded.',
  VSUP_BACKEND_UNAVAILABLE: 'No backend could be selected, or the launcher interpreter is missing.',
  VSUP_BACKEND_CRASHED: 'The Vibe process exited before the turn finished.',
  VSUP_TIMEOUT: 'The run deadline elapsed.',
  VSUP_RATE_LIMITED: 'Vibe or its provider answered with HTTP 429.',
  VSUP_CANCELLED: 'The run was cancelled, or it never started because the supervisor stopped first.',
  VSUP_OUTPUT_LIMIT: 'The run exceeded an event, transcript or artifact byte limit.',
  VSUP_ARTIFACT_ERROR: 'A run artifact could not be written, read or exported.',
  VSUP_INVALID_ARGUMENT: 'The tool arguments failed schema validation.',
  VSUP_NOT_FOUND: 'No run with that ID exists.',
  VSUP_BACKEND_ERROR: 'The backend reported a failure that has no more specific code.',
  VSUP_LIMIT_EXCEEDED: 'No run slot or queue capacity is free.',
  VSUP_PERMISSION_DENIED: 'The worker asked for an action outside the safety policy, or a chosen permission option was refused; no decision is pending.',
  VSUP_NO_PROGRESS: 'A running worker emitted no event for limits.worker_progress_timeout_seconds, so the supervisor ended the run.',
  VSUP_TURN_LIMIT_REACHED: "The run's last turn ended at Vibe's cumulative turn limit and the continuation did not raise it.",
  VSUP_INVALID_STATE: 'The action is not valid in the run state, or the data directory is owned by another supervisor.',
  VSUP_STORAGE_ERROR: 'A filesystem fault (disk full, permissions, read-only, I/O) hit the data directory.',
  VSUP_RECOVERY_ERROR: 'A saved run could not be recovered.',
  VSUP_INTERNAL: 'An unexpected supervisor failure; the detail is only on stderr.',
};

const RETRYABLE = new Set(['VSUP_RATE_LIMITED']);

const cell = (text) => text.replaceAll('|', '\\|').replace(/\s+/g, ' ').trim();

export function renderErrorsDoc(remediation) {
  const codes = Object.keys(remediation);
  const rows = codes.map((code) => `| \`${code}\` | ${cell(MEANINGS[code] ?? '')} | ${cell(remediation[code])} | ${RETRYABLE.has(code) ? 'yes' : 'no'} |`);
  return [
    '# Error codes',
    '',
    'Generated by `npm run docs:errors` from `REMEDIATION` in `src/contracts.ts`; do not edit by hand.',
    '',
    'An error carries `code`, `message`, `remediation`, `retryable` and sometimes `details`. `retryable` is `true` only when the failure is transient; every other code reports `false` unless the backend marks it otherwise. Failures that are not supervisor errors reach the client as `VSUP_INTERNAL` without detail.',
    '',
    '| Code | Meaning | Remedy | Retryable |',
    '|---|---|---|---|',
    ...rows,
    '',
  ].join('\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const { REMEDIATION } = await import(pathToFileURL(path.join(root, 'dist', 'contracts.js')).href);
  const text = renderErrorsDoc(REMEDIATION);
  if (process.argv.includes('--check')) {
    const current = await readFile(errorsDocPath, 'utf8').catch(() => '');
    if (current !== text) { process.stderr.write('docs/errors.md is out of date; run npm run docs:errors.\n'); process.exitCode = 1; }
  } else await writeFile(errorsDocPath, text);
}
